Sage-Bionetworks/BridgeDownstream

- .github/workflows/aws-deploy.yaml
- .github/workflows/upload-python.yaml
- src/glue/jobs/json_s3_to_parquet.py
This adds an additional workflow for the purpose of uploading python scripts to a bucket. This is necessary b/c the Glue jobs want to pull scripts from an S3 bucket.
This CICD workflow adds more complexity than I would like, but the current configuration of workflow scripts seems to be behaving itself for the moment.
> Etl-55 scripts workflow

- .github/workflows/upload-glue-scripts.yaml
This is a refinement on the scripts workflow
1. Fixes an issue with the bucket directory setting
2. Alters the workflow to only trigger if path changes match pattern 'src/glue/jobs/*.py' rather than all py files. This will be necessary if we are going to keep the lambda in the same repository, or it will also trigger this workflow. It needs its own, separate workflow.
> Etl-55 scripts workflow part. 2

- config/develop/glue-jobs.yaml
- config/develop/s3-intermediate-bucket.yaml
- config/develop/s3-parquet-bucket.yaml
- config/develop/s3-source-bucket.yaml
Slight bucket refactor in preparation for workflow PR
Instead of just input/output buckets,
renamed input to source
renamed output to parquet
created a bucket called "intermediate" for the unpacked json and the job temp dir
> Etl-68/buckets

- config/develop/glue-workflows.yaml
- templates/glue-workflows.yaml
Add the workflows component of the pipeline.
The workflows and jobs will be joined up in the triggers stack.
depends on #13 
(note that this PR uses dpulls to indicate dependencies between PRs -- it is normal for this to fail on the dpulls check until the other is merged)
> ETL-68 Add workflows stack

- config/develop/glue-jobs.yaml
- config/develop/glue-triggers.yaml
- config/develop/glue-workflows.yaml
- config/develop/s3-intermediate-bucket.yaml
- config/develop/s3-parquet-bucket.yaml
- config/develop/s3-source-bucket.yaml
- templates/glue-jobs.yaml
- templates/glue-triggers.yaml
- templates/glue-workflows.yaml
This defines triggers that associates workflows to jobs; have also had to add several outputs and decided to make stack dependencies explicit.
Currently both triggers are of type ON_DEMAND but I anticipate at least one of these will change in the future. 
Depends on #14
> Etl-69 Triggers

- templates/glue-job.yaml
- templates/glue-jobs.yaml
Fix problem with re-deploying glue-jobs: if we use static names in the stacks they won't create a new version; instead make the job names dependent upon the stackname.
> Make job names dependent upon stack name

- .github/workflows/upload-and-deploy.yaml
- src/glue/jobs/s3_to_json_s3.py
- src/glue/resources/dataset_mapping.json
This addresses https://sagebionetworks.jira.com/browse/ETL-74
* Added a dataset mapping file. Right now the only app version present in the file is the most recent test build, version 1.0.2, build 57
* Added a function to get the dataset mapping file from S3 and reference it when bucketing the JSON file. The location of the dataset mapping file is assumed to be in the same bucket as the `s3_to_json_s3` job script (as deployed by sceptre) and the key is hardcoded to its deployment location. I updated the deployment configuration so that both glue jobs and their resources (just dataset_mapping file, so far...) are included in the sceptre deployment.
> Add dataset mapping and reference it in s3_to_json_s3 script

- config/develop/glue-jobs.yaml
- config/develop/study-example-1.yaml
- config/develop/study-example-2.yaml
- templates/glue-jobs.yaml
- templates/glue-python-job.yaml
- templates/glue-spark-job.yaml
- templates/study-pipeline-infra.yaml
Introduce a uniquish value for job names so that replacement can happen without dependent stacks complaining. This may be overkill since I'm also decoupling the stacks by replacing CFN ImportValue with sceptre params.
> ETL-85: unique job names / stack decoupling

- src/scripts/archive_dataset/archive_dataset.py
- src/scripts/backfill_json_datasets/backfill_json_datasets.py
- src/scripts/flip_job/flip_job.py
- src/scripts/get_representative_sample/get_representative_sample.py
Addresses: https://sagebionetworks.jira.com/browse/ETL-89
Also added module comments to the top of the other scripts I wrote
in the past few weeks. Additionally, extended backfill_json_datasets
to use cached Synapse credentials if an ssm-parameter name is not
passed.
> Initial commit archive_dataset script

- templates/glue-database.yaml
Removing a block from the Glue table configurations that seems to be unnecessary. The pipeline's working fine without it. The advantage of removing it is that this is a portion of the configuration that doesn't have to be updated when there's a schema change.
> Remove explicit SerdeInfo config from Glue tables

- CONTRIBUTING.md
- config/develop/glue-jobs.yaml
- config/develop/study-example-1.yaml
- config/develop/study-example-2.yaml
- templates/glue-jobs.yaml
- templates/glue-python-job.yaml
- templates/glue-spark-job.yaml
This enables the Spark UI for Spark jobs -- the config options is a bit misnamed. Actually it just saves the spark logs so you can ingest them into Spark History Server. I also added CONTRIBUTING.md to explain how to spin up a docker container for that.
> ETL-99/spark UI

- .github/workflows/cleanup.yaml
I believe cleanup.yaml has an error in its syntax that is causing its stack names to fail to resolve properly -- attempting to fix this.
> Fix syntax issue preventing variable from being expanded

- .github/workflows/cleanup.yaml
Changes syntax in cleanup.yaml to use github expression instead of an environment variable in an effort to fix bug when deleting sceptre stacks.
> Use github action expression instead of bash environment variable

- .github/workflows/cleanup.yaml
The problem with the cleanup.yaml has been that the `ref_name` field of the DELETE event's payload is _not_ the name of the branch being deleted -- it is `main`. To get the name of the branch being deleted, use `event.ref`.
> Use the correct ref name from the delete event when cleaning up

- .pre-commit-config.yaml
- config/develop/namespaced/sqs-queue.yaml
- config/develop/sqs-queue.yaml
- templates/sqs-queue.yaml
This is just the SQS CFN template and an example config. The other work we've been doing (including moving the lambda to its own stack) will be included in the PR for ETL-117.
> [ETL-107] Add SQS template and config

- .github/workflows/upload-and-deploy.yaml
- config/config.yaml
- config/develop/namespaced/example-app-1-study-1.yaml
- config/develop/namespaced/glue-job-S3ToJsonS3.yaml
- config/develop/namespaced/sqs-to-glue-lambda.yaml
- config/develop/sqs-to-glue-lambda.yaml
- src/lambda/template.yaml
- src/lambda/test-env-vars.json
- templates/sqs-queue.yaml
- templates/study-pipeline-infra.j2
* Lambda has been pulled out of the study stack and is now in its own stack
* "sns to glue" nomenclature has been changed to "sqs to glue"
* Both Lambda and SQS queue are namespaced
* Lambda has permissions to invoke any glue workflow, not just one associated with a specific study or namespace
* The commit which used to be in this branch which changed the test events from SQS events to SNS events has been omitted (i.e., they're SQS events again). I'm not sure why I thought we would be passing those test events to the SQS queue rather than our lambda...
> [ETL-117] Lambda polls from SQS queue

- src/glue/jobs/json_s3_to_parquet.py
We have had issues with field types not resolving correctly (see [ETL-238](https://sagebionetworks.jira.com/browse/ETL-238)), but the DynamicFrame method to solve this does not work as you would expect in every case. Nevertheless, it's the best solution we have at the moment.
Highlights include:
* An added method call to `DynamicFrame.resolveChoice(choice="match_catalog", ...)` to attempt to resolve the `ChoiceType` fields in the DynamicFrame to the types in the corresponding Glue table. This is the function which doesn't always work.
* A big refactor of the rest of the JSON to Parquet job so it's less monolithic and has docstrings.
> [ETL-239] Refactor JSON to Parquet job and attempt to match types

- Pipfile.lock
- config/develop/glue-job-role.yaml
- config/prod/glue-job-role.yaml
- templates/glue-job-role.yaml
Instead of using a managed policy, I've made the permissions that our Glue job and crawlers have explicit. I basically used the same permissions in the previously used managed policy, but I've modified some of them to better fit our pipeline (specifically, the S3 permissions). I also updated the Pipfile.lock, which should have been done in #94 .
> [ETL-255] Explicit Glue resource permissions

- config/prod/s3-parquet-bucket.yaml
There was an incorrect dependency specified in our prod stack for a very long time... it hasn't caused any issues until, apparently, now and is blocking #95 !
> Fix incorrect dependency in prod parquet bucket

- config/config.yaml
- config/prod/s3-parquet-bucket.yaml
Jinja and CFN do not play nicely here so we need to go back to explicitly specifying this parameter in the config file.
> Revert changes to config synapseBridgeDownstreamUserId parameter

- config/develop/namespaced/glue-job-S3ToJsonS3.yaml
- config/prod/glue-job-S3ToJsonS3.yaml
One more stack fix. The Glue job role dependency was not included in the S3 to JSON stack which depends on it. This hadn't broken earlier since this stack also depends on the intermediate bucket stack, and we only just now removed the glue job role dependency from that stack.
> Add missing glue-job-role dependency to S3 to JSON stack

- src/scripts/bootstrap_trigger/bootstrap_trigger.py
Add a `--drop-duplicates` flag to the bootstrap trigger script so that only the most recently exported Synapse file with a given record ID is submitted to the Glue workflow. Also added docstrings.
> [ETL-261] Add `--drop-duplicates` functionality to the bootstrap trigger script

- .github/workflows/upload-and-deploy.yaml
- tests/test_json_s3_to_parquet.py
Addresses:
* The glue resource files – specifically schema and dataset “legacy” mappings – should be uploaded to the artifact bucket either before the unit tests run or the tests should use mocked resources. (I've moved the upload step prior to the unit test step).
* The glue crawler should use the `json_s3_objects fixture` so that we know that the test data are in S3 before we run the crawler. (I made the crawler a standard, function-scoped fixture since we just need it to run once and have no need to reference it afterwards. This allows it to use the `json_s3_objects` fixture since it is no longer class-scoped.)
> [ETL-256] Address unit test concurrency issues

- .github/workflows/upload-and-deploy.yaml
- src/glue/jobs/s3_to_json_s3.py
- tests/test_s3_to_json_s3.py
* Ignores Android validation errors as outlined in ETL-312.
* Minor refactor of Github upload-and-deploy workflow.
[ETL-312]: https://sagebionetworks.jira.com/browse/ETL-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ETL-312] Ignore specific non-severe Android validation errors

- src/glue/jobs/s3_to_json_s3.py
- tests/test_s3_to_json_s3.py
Removes anticipated (Android) validation errors from validation error result. This makes the validation process slightly more forgiving, but the only validation errors we ignore are concerned with missing required properties, superfluous properties, and a mis-specified value in motion ("acceleration" instead of "accelerometer" or "userAcceleration") -- so there shouldn't be any issues with mis-matched parquet dataset schemas.
Tested with the [data from the E2E QA study](https://www.synapse.org/#!Synapse:syn51121831/tables/) and [our test dataset](https://www.synapse.org/#!Synapse:syn29276125/datasets/).
> [ETL-358] Remove expected validation errors in S3 to JSON S3 validation result

- src/scripts/JIRA/etl-437/main.py
This script is meant to resolve the issues we've had processing JSON whose filename begins with an underscore. Originally, I wanted to move the objects by doing a copy followed by a delete, but according to [this doc](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html) it might be complicated determining if a copy operation was completed successfully. So I decided to drop the "delete" action, this way if there are any issues we haven't inadvertently chucked the original data.
> [ETL-437] Add script to copy (underscore) S3 objects to new object

- src/scripts/add_targets_to_crawler/add_targets_to_crawler.py
This module provides functions to update a glue crawler by adding additional s3 targets and (potentially) modifying the recrawl policy. If a glue crawler is configured to crawl new folders only, it cannot be updated via a regular stack update. Instead, we need to perform the following steps to completed the update:
1. Perform the desired crawler updates, but ensure that the update has a recrawl policy of crawl_everything so that the update completes successfully.
2. If the crawler originally had a different recrawl policy, we can "undo" the change to the recrawl policy we made in the previous step by doing an additional update -- but only to set the recrawl policy back to its original value
This script supports a specific use case which occurs when we add support for new datasets. …
> [ETL-453] Add module to update Glue crawlers with additional targets

- src/scripts/validate_synapse_records/validate_synapse_records.py
This script validates record data against its schema by querying a Synapse file view for records. The records must use the self-referencing format in their metadata.json file. Any files in the record which do not have a `jsonSchema` property specified in their fileInfo object in metadata.json will not be validated. The validation results are written to `validation_errors.json`.
> [ETL-440] Add script to validate self-referencing records on Synapse

- src/glue/jobs/s3_to_json_s3.py
- src/glue/resources/table_columns.yaml
- tests/test_s3_to_json_s3.py
This fixes the mistake I introduced when overwriting the json schema `$id`. I made some other fixes to make the job less dumb. Details in the comments.
I ran the new assessments and the test dataset through this pipeline and read all the parquet datasets produced from the JSON, so I'm pretty confident this works.
> [ETL-458] Fixes for S3 to JSON, Glue tables

- src/glue/jobs/s3_to_json_s3.py
We've had issues with file names that begin with an underscore. The same root cause also affects file names that begin with periods, so I added that to the conditional out of an abundance of caution.
> [ETL-444] Append a 0 (zero) in front of underscore/period records file names
