Sage-Bionetworks/BridgeDownstream

scripts/backfill_json_datasets/backfill_json_datasets.py
Addresses https://sagebionetworks.jira.com/browse/ETL-61
=> bootstrap json dataset by submitting existing archives

config/develop/glue-crawler.yaml, templates/glue-crawler.yaml, templates/glue-database.yaml, templates/glue-json-classifier.yaml
This creates the Glue crawler -- @philerooski please verify this is what we want
=> Etl-70 Glue crawler

src/scripts/backfill_json_datasets/backfill_json_datasets.py
This addresses https://sagebionetworks.jira.com/browse/ETL-86
Added some functionality so that instead of passing an entire folder of files we can pass an entity view and query in order to submit specific files to the workflow.
=> Extend backfill json datasets script to accept entity view

src/scripts/get_representative_sample/get_representative_sample.py
This addresses https://sagebionetworks.jira.com/browse/ETL-87
=> Add script to build query string for representative appVersion sample

src/scripts/flip_job/flip_job.py
Addresses https://sagebionetworks.jira.com/browse/ETL-88
Disable or enable a job by removing it from its trigger's actions
=> Initial commit flip_job script

src/scripts/setup_test_data/setup_test_data.py
Check whether storage location already configured before trying to do so in setup_test_data; 
also, only process files not already added..
=> fixing storage location handling in setup_test_data

src/glue/jobs/s3_to_json_s3.py, src/scripts/setup_test_data/setup_test_data.py
Resolves ETL-97: https://sagebionetworks.jira.com/browse/ETL-97
=> Use uploadedOn rather than createdOn for derived year/month/day partition fields

src/glue/resources/dataset_crawler_assignments.yaml, src/glue/resources/dataset_mapping.json, src/glue/resources/table_columns.yaml
Minor fix of info dataset version.
=> Fix info version in config files

config/develop/example-app-1-study-1.yaml
Minor fix to branch used for templates and scripts.
=> Correct branch in example study sceptre config

src/lambda/README.md, src/lambda/sns_to_glue/app.py, src/lambda/template.yaml, src/lambda/test-env-vars.json, templates/study-pipeline-infra.j2
Lambda script must take namespace into account when calling workflow
=> Fix lambda issue with namespaces

config/develop/namespaced/sqs-to-glue-lambda.yaml, src/glue/jobs/json_s3_to_parquet.py, src/glue/jobs/s3_to_json_s3.py, src/glue/resources/table_columns.yaml
Record ID is still included as a field in every record, but it is no longer included in the partitions.
=> [ETL-109] Remove record ID from partitions

.github/workflows/upload-and-deploy.yaml, config/develop/ecr-repository.yaml, src/lambda/sns_to_glue/Dockerfile, src/lambda/sns_to_glue/requirements.txt, src/lambda/template.yaml
* Lambda is built as a .zip file archive.
* Resources related to the lambda docker image were removed
=> [ETL-166] De-dockerize lambda

src/lambda/README.md, src/scripts/setup_test_data/setup_test_data.py
Once @mattfazza is able to try their hand at invoking the lambda with the test events we can incorporate their feedback into this PR before merging.
=> [ETL-177] Update lambda README and copy relevant info to setup_test_data.py

src/scripts/manage_artifacts/artifacts.py
This should have been included with #66
=> Upload lambda template to CFN bucket

config/develop/namespaced/example-app-1-study-1.yaml, config/develop/vpc.yaml, config/prod/vpc.yaml
I think putting the EC2 in one of the private subnets created by this plus adding the AmazonSSMManagedInstanceCore policy on the EC2 will allow me to securely interface with the EC2. Please review.
=> [ETL-176] Create VPC with private subnets

src/scripts/bootstrap_trigger/bootstrap_trigger.py
* Fix and simplify parquet diff process
* Improved argument descriptions and defaults
=> [ETL-198] Fix parquet diff and simplify bootstrap trigger

src/glue/jobs/s3_to_json_s3.py
This should have been included with #84
=> Fix type of assessment revision when referencing archive mapping

config/develop/cfn-s3objects-macro.yaml, config/develop/glue-job-role.yaml, config/develop/namespaced/example-app-1-study-1.yaml, config/develop/namespaced/glue-classifier-array-of-records.yaml, config/develop/namespaced/glue-job-S3ToJsonS3.yaml, config/develop/namespaced/invalid-sqs-queue.yaml, config/develop/namespaced/sqs-queue.yaml, config/develop/pytest-ecr-repository.yaml, config/develop/s3-intermediate-bucket.yaml, config/develop/s3-parquet-bucket.yaml, config/develop/vpc.yaml, config/prod/cfn-s3objects-macro.yaml, config/prod/ec2-bootstrap-trigger.yaml, config/prod/glue-classifier-array-of-records.yaml, config/prod/glue-job-S3ToJsonS3.yaml, config/prod/glue-job-role.yaml, config/prod/invalid-sqs-queue.yaml, config/prod/s3-intermediate-bucket.yaml, config/prod/s3-parquet-bucket.yaml, config/prod/studies/mobile-toolbox-cxhnxd.yaml, config/prod/studies/mobile-toolbox-fmqcjv.yaml, config/prod/studies/mobile-toolbox-hktrrx.yaml, config/prod/studies/mobile-toolbox-htshxm.yaml, config/prod/studies/mobile-toolbox-mtb-alpha.yaml, config/prod/studies/mobile-toolbox-pmbfzc.yaml, config/prod/vpc.yaml
Updates all config files replace template_path with template
=> [ETL-111] update config template handler

config/develop/namespaced/glue-job-S3ToJsonS3.yaml, src/glue/jobs/s3_to_json_s3.py, src/glue/resources/dataset_crawler_assignments.yaml, src/glue/resources/schema_mapping.json, src/glue/resources/table_columns.yaml
* Added GradualOnsetV1 table to `table_columns.yaml`
* Updated `schema_mapping.yaml` and `crawler_assignments.yaml`
* Upgraded to archive-map.json v4.5.2 in S3 to JSON job
* Update S3 to JSON job to support new archive-map.json format.
=> [ETL-301] Support new schema for GradualOnsetV1 assessment

tests/test_s3_to_json_s3.py
This should have been part of #109 . Forgot to update the tests!
=> Update tests to use latest archive map format

src/scripts/bootstrap_trigger/bootstrap_trigger.py
If S is the set of records on Synapse, P1 the set of records in the first Parquet dataset and P2 the set of records in the second Parquet dataset, I was doing
```
S \ (P1 U P2)
```
When I should have been doing
```
(S \ P1) U (S \ P2)
```
=> [ETL-425 fix] Update bootstrap trigger to use correct set logic

.github/workflows/upload-and-deploy.yaml
Fix for broken action resulting from pulling in #140
=> Clean up "matrix" component of upload-and-deploy workflow

.github/workflows/upload-and-deploy.yaml
I should not have deleted this line in #141 
```
environment: ${{ matrix.job-environment }}
```
=> [PATCH] Clean up "matrix" component of upload-and-deploy workflow

src/glue/jobs/s3_to_json_s3.py, tests/test_s3_to_json_s3.py
**Purpose:** Adds a new expected validation error for `motion.json` to the S3 to JSON job
=> [ETL-487] Add new expected error for motion.json

tests/test_json_s3_to_parquet.py
If it does, delete the resource (or detach and delete in the case of an IAM role).
=> [ETL-485] Check if test resource exists before creating
